### ISSUE TITLE
Customstructures not enabling on purpur 1.17.1

### ISSUE THREAD

**Issue by The-Nyla** [ryandw11/CustomStructures#118]
**Describe the bug**
The plugin fails to enable upon server startup or through use of a plugin manager

**Steps to Reproduce**
download pupur, install customstructures, and start a server

**Expected behavior**
I expected the plugin to enable correctly

**Screenshots**

**Structure File(s)**
No structure files other than the default

**Environment Information:**
 - Minecraft Version: 1.17.1
 - Spigot Version: pupur 1.17.1, build 1383
 - Custom Structures Version: 1.6.1
 - World Edit Version: fast async worldedit 1.17-157;6a932f2

**Additional context**
Error log:

[16:55:06 INFO]: [CustomStructures] Enabling CustomStructures v1.6.1
[16:55:06 WARN]: Enabled plugin with unregistered PluginClassLoader CustomStructures v1.6.1
[16:55:06 INFO]: [CustomStructures] MythicMobs detected! Activating plugin hook!
[16:55:06 ERROR]: Error occurred while enabling CustomStructures v1.6.1 (Is it up to date?)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1a5430cc[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@134e4ea9[Wrapped task = com.ryandw11.structure.bstats.MetricsBase$$Lambda$8510/0x0000000802ae4f90@6e054918]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@61caa353[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2057) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:827) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562) ~[?:?]
	at com.ryandw11.structure.bstats.MetricsBase.startSubmitting(MetricsBase.java:134) ~[CustomStructures-1.6.1.jar:?]
	at com.ryandw11.structure.bstats.MetricsBase.<init>(MetricsBase.java:107) ~[CustomStructures-1.6.1.jar:?]
	at com.ryandw11.structure.bstats.bukkit.Metrics.<init>(Metrics.java:74) ~[CustomStructures-1.6.1.jar:?]
	at com.ryandw11.structure.CustomStructures.onEnable(CustomStructures.java:120) ~[CustomStructures-1.6.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Purpur-1383]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1383]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.frankheijden.serverutils.bukkit.managers.BukkitPluginManager.enableOrderedPlugins(BukkitPluginManager.java:184) ~[ServerUtils-3.0.0.jar:?]
	at net.frankheijden.serverutils.bukkit.dependencies.su.common.managers.AbstractPluginManager.enablePlugins(AbstractPluginManager.java:105) ~[ServerUtils-3.0.0.jar:?]
	at net.frankheijden.serverutils.bukkit.commands.BukkitCommandServerUtils.handleEnablePlugin(BukkitCommandServerUtils.java:100) ~[ServerUtils-3.0.0.jar:?]
	at net.frankheijden.serverutils.dependencies.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:60) ~[ServerUtils-3.0.0.jar:?]
	at net.frankheijden.serverutils.dependencies.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:121) ~[ServerUtils-3.0.0.jar:?]
	at net.frankheijden.serverutils.dependencies.cloud.CommandManager.executeCommand(CommandManager.java:178) ~[ServerUtils-3.0.0.jar:?]
	at net.frankheijden.serverutils.dependencies.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:107) ~[ServerUtils-3.0.0.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-1383]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2316) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2127) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2108) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1433) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1411) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1382) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1293) ~[patched_1.17.1.jar:git-Purpur-1383]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1383]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[16:55:06 INFO]: [CustomStructures] Disabling CustomStructures v1.6.1
[16:55:06 ERROR]: [CustomStructures] ERROR: The Structure Handler was never initialized during setup.

**Comment by ryandw11** [comment]
Thanks for the report.
