### ISSUE TITLE
Error when creating the structure

### ISSUE THREAD

**Issue by Steyn911** [ryandw11/CustomStructures#125]
**Describe the bug**
The plugin loads, but i can't create structure

**Steps to Reproduce**
I created a test schematic and after executing the command "/cstruct create test test" the plugin sends this message to the chat: 

"An internal error occured while attempting to perform this command"

And this mesage to the console:

[21:52:25] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cstruct' in plugin CustomStructures v1.6.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/HeightMap
        at com.ryandw11.structure.structure.properties.StructureLocation.<init>(StructureLocation.java:82) ~[?:?]
        at com.ryandw11.structure.commands.cstruct.CreateCommand.subCommand(CreateCommand.java:79) ~[?:?]
        at com.ryandw11.structure.commands.CommandHandler.handleCommand(CommandHandler.java:69) ~[?:?]
        at com.ryandw11.structure.commands.SCommand.onCommand(SCommand.java:62) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.HeightMap
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at com.ryandw11.structure.structure.properties.StructureLocation.<init>(StructureLocation.java:82) ~[?:?]
        at com.ryandw11.structure.commands.cstruct.CreateCommand.subCommand(CreateCommand.java:79) ~[?:?]
        at com.ryandw11.structure.commands.CommandHandler.handleCommand(CommandHandler.java:69) ~[?:?]
        at com.ryandw11.structure.commands.SCommand.onCommand(SCommand.java:62) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        ... 17 more

I also noticed this error when the plugin tries to load the example structure on server starting:

[22:29:55] [Server thread/INFO]: [CustomStructures] Loading structures from files.
[22:29:55] [Server thread/WARN]: [CustomStructures] Task #3 for CustomStructures v1.6.1 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/HeightMap
        at com.ryandw11.structure.structure.properties.StructureYSpawning.<init>(StructureYSpawning.java:36) ~[?:?]
        at com.ryandw11.structure.structure.properties.StructureLocation.<init>(StructureLocation.java:37) ~[?:?]
        at com.ryandw11.structure.structure.StructureBuilder.<init>(StructureBuilder.java:121) ~[?:?]
        at com.ryandw11.structure.structure.StructureHandler.<init>(StructureHandler.java:53) ~[?:?]
        at com.ryandw11.structure.CustomStructures.lambda$onEnable$1(CustomStructures.java:101) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.HeightMap
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 12 more

**Expected behavior**
Generating a structure

**Screenshots**

**Structure File(s)**
Please put any related structure files in a pastebin (https://pastebin.com/) and provide a link.

**Environment Information:**
 - Minecraft Version: 1.14.4
 - Spigot Version: 1.14.4
 - Custom Structures Version: 1.6.1
 - World Edit Version: 7.2.0

**Additional context**

**Comment by ryandw11** [comment]
This issue should be resolved in the latest version. If the issue persists, please open another issue.
