### ISSUE TITLE
1.18

### ISSUE THREAD

**Issue by soupcoup** [ryandw11/CustomStructures#127]
are there any plans to update to 1.18 or a snapshot build i could use?

**Comment by ryandw11** [comment]
Custom Structures should work on 1.18 without breaking. I have not tested it yet as WorldEdit just released for 1.18. An update will be coming out in the near future though.

**Comment by soupcoup** [comment]
i will give you more specifics when i recreate the environment but upon updating i received an error when doing /cs test (structurename) i decided to downgrade and wait because its more worthwhile or i would be able to give you console logs rn
(although it could be any number of things from paper being a snapshot rn other plugins etc)

**Comment by marcelschoen** [comment]
I just tried it on PaperMC 1.18. It currently crashes with this error:

2021-12-06 23:42:25 [WARN] Task #1064 for CustomStructures v1.7.0 generated an exception
java.lang.RuntimeException: com.sk89q.worldedit.bukkit.adapter.UnsupportedVersionEditException: Editing on unsupported versions is disabled.
	at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:457) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.getFullBlock(BukkitWorld.java:491) ~[?:?]

**Comment by ryandw11** [comment]
That looks like a world edit issue. Do you have the full error?

**Comment by marcelschoen** [comment]
```
2021-12-07 00:10:01 [WARN] Schematic was made in a newer Minecraft version (2730 > -1). Data may be incompatible.
2021-12-07 00:10:01 [WARN] Task #765 for CustomStructures v1.7.0 generated an exception
java.lang.RuntimeException: com.sk89q.worldedit.bukkit.adapter.UnsupportedVersionEditException: Editing on unsupported versions is disabled.
	at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:457) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.getFullBlock(BukkitWorld.java:491) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
	at com.sk89q.worldedit.extent.cache.LastAccessExtentCache.getFullBlock(LastAccessExtentCache.java:66) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractBufferingExtent.getFullBlock(AbstractBufferingExtent.java:68) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractBufferingExtent.getFullBlock(AbstractBufferingExtent.java:68) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
	at com.sk89q.worldedit.extent.ChangeSetExtent.setBlock(ChangeSetExtent.java:64) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
	at com.sk89q.worldedit.extent.MaskingExtent.setBlock(MaskingExtent.java:69) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
	at com.sk89q.worldedit.extent.validation.BlockChangeLimiter.setBlock(BlockChangeLimiter.java:87) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
	at com.sk89q.worldedit.extent.validation.DataValidatorExtent.setBlock(DataValidatorExtent.java:64) ~[?:?]
	at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:737) ~[?:?]
	at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:780) ~[?:?]
	at com.sk89q.worldedit.function.block.ExtentBlockCopy.apply(ExtentBlockCopy.java:79) ~[?:?]
	at com.sk89q.worldedit.function.RegionMaskingFilter.apply(RegionMaskingFilter.java:53) ~[?:?]
	at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:60) ~[?:?]
	at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[?:?]
	at com.sk89q.worldedit.function.operation.DelegateOperation.resume(DelegateOperation.java:52) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.complete(Operations.java:41) ~[?:?]
	at com.ryandw11.structure.SchematicHandler.schemHandle(SchematicHandler.java:151) ~[?:?]
	at com.ryandw11.structure.SchematicHandler.schemHandle(SchematicHandler.java:230) ~[?:?]
	at com.ryandw11.structure.utils.StructurePicker.lambda$run$1(StructurePicker.java:213) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.jar:git-Paper-55]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.jar:git-Paper-55]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1547) ~[paper-1.18.jar:git-Paper-55]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480) ~[paper-1.18.jar:git-Paper-55]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470) ~[paper-1.18.jar:git-Paper-55]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264) ~[paper-1.18.jar:git-Paper-55]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-55]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.sk89q.worldedit.bukkit.adapter.UnsupportedVersionEditException: Editing on unsupported versions is disabled.
	... 40 more

```

**Comment by marcelschoen** [comment]
I am using the "worldedit-bukkit-7.2.7.jar".

**Comment by marcelschoen** [comment]
You are correct. I just tried to just copy a small block in my world with WorldEdit, and I get an error in the game console:

`This WorldEdit version does not fully support your version of Bukkit....`

**Comment by marcelschoen** [comment]
Have you already successfully tested "CustomStructures" on 1.18? If so, what version of WorldEdit did you use?

**Comment by marcelschoen** [comment]
Anyway, I guess I'll have to find a version of WorldEdit that works... maybe a snapshot build...

**Comment by marcelschoen** [comment]
Got it working! I downloaded a snapshot build of "WorldEdit" from here:

https://builds.enginehub.org/job/worldedit?branch=version/7.2.x

I downloaded the "worldedit-bukkit-7.2.8-SNAPSHOT-dist.jar", and with that, "CustomStructures" works!

**Comment by marcelschoen** [comment]
I guess you can close this issue since "CustomStructures" definitely works on my PaperMC 1.18.
