### ISSUE TITLE
Mythic Mobs with Custom Structures breaks

### ISSUE THREAD

**Issue by Gyztor** [ryandw11/CustomStructures#140]
**Describe the bug**
When i attempt to spawn a mob with the [mythicmobs] tag the plugin seems to load fine until when a structure generates it shows an error
```
[21:14:53 WARN]: [CustomStructures] Task #12484 for CustomStructures v1.7.1.1 generated an exception
java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/MythicMobs
        at com.ryandw11.structure.mythicalmobs.MMEnabled.spawnMob(MMEnabled.java:12) ~[CustomStructures-1.7.1.1 (1).jar:?]
        at com.ryandw11.structure.SchematicHandler.processAndReplaceSign(SchematicHandler.java:636) ~[CustomStructures-1.7.1.1 (1).jar:?]
        at com.ryandw11.structure.SchematicHandler.lambda$schemHandle$0(SchematicHandler.java:198) ~[CustomStructures-1.7.1.1 (1).jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-315]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-315]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-315]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-315]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-315]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-315]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-315]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.MythicMobs
        ... 11 more
```

**Steps to Reproduce**
Take a schematic and add [mythicmob] and whatever mob you want. add it to a structure. reload the plugin and test spawn the structure. only signs will exist and no mobs

**Expected behavior**
When adding the tag it just spawns the mythicmob i set it to spawn in the certain places.

**Screenshots**

**Structure File(s)**
[Please put any related structure files in a pastebin (https://pastebin.com/) and provide a link.](https://pastebin.com/WfErLpNB)

**Environment Information:**
 - Minecraft Version: 1.18.2
 - Spigot Version: Paper-315 (1.18.2)
 - Custom Structures Version: 1.7.1.1
 - World Edit Version: FAWE 2.1.3-SNAPSHOT-168;210ee9f

**Additional context**
I also have the heroes plugin installed but i am doubtful that would really be doing anything because this even happens in areas that aren't controlled by heroes

**Comment by ryandw11** [comment]
You can use this developer build as a temporary fix: https://ci.ryandw11.com/job/custom-structures-dev/.

**Comment by Gyztor** [comment]
fixed my issue, thank you!
