### ISSUE TITLE
Schem error (containers and mobs)

### ISSUE THREAD

**Issue by Yesu321** [ryandw11/CustomStructures#175]
Schemes do not allow signs or containers, if I use a container even if it is empty, I get an error when using the command to create a schem, the same thing happens if instead of a container I put a sign to generate a mob, I get an error in the chat that says An internal error occurred while attemping to perform this command

I built a structure with a sign for a mob to spawn and marked it with the worldedit axe, but when I finally went to create the schema with the command /cstructure createSchem (name), I got an error, then I tried removing the sign to see Yes, it was the problem and I noticed that when I removed the sign I could save the shem, but i need  the containers and mobs for my structures :/

![2024-06-15_10 56 54](https://github.com/ryandw11/CustomStructures/assets/172917541/67e5aef9-0f0f-49bf-9386-4eb47ec96e3f)

 - Minecraft Version: 1.20
 - Spigot Version: 1.20 (3871)
 - Custom Structures Version: 1.9.0.1
 - World Edit Version:  worldedit 7.3.0 beta 03

**Comment by ryandw11** [comment]
When you run the command, an error trace should show up in the console. Can you share that error here?

**Comment by Yesu321** [comment]
> Cuando ejecuta el comando, debería aparecer un seguimiento de error en la consola. ¿Puedes compartir ese error aquí?

[19:30:06] [Server thread/INFO]: 
Sign Spy 
- Location: 
x: 5718158, y: 123, z: -10750598, world: world
[19:30:06] [Server thread/INFO]: 
Player: 
Yesu
[19:30:06] [Server thread/INFO]: 
Lines - 
1: 
[mob] - 
2: 
zombie
[19:30:06] [Server thread/INFO]: 
Lines - 
3: 
 - 
4: 
[19:30:43] [Server thread/INFO]: Yesu issued server command: /cstructure createSchem das
[19:30:43] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cstructure' in plugin CustomStructures v1.9.0.1
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:877) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:?]
at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:314) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:298) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1924) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1151) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1123) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1107) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1018) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalAccessError: class com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R1.PaperweightAdapter tried to access private field net.minecraft.nbt.NBTTagCompound.x (com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R1.PaperweightAdapter is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @f7915a7; net.minecraft.nbt.NBTTagCompound is in unnamed module of loader java.net.URLClassLoader @6a4f1a55)
at com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R1.PaperweightAdapter.toNative(PaperweightAdapter.java:1003) ~[?:?]
at com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R1.PaperweightAdapter.lambda$getFullBlock$1(PaperweightAdapter.java:397) ~[?:?]
at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:83) ~[?:?]
at com.sk89q.worldedit.world.NbtValued.getNbt(NbtValued.java:119) ~[?:?]
at com.sk89q.worldedit.function.block.ExtentBlockCopy.transformNbtData(ExtentBlockCopy.java:90) ~[?:?]
at com.sk89q.worldedit.function.block.ExtentBlockCopy.apply(ExtentBlockCopy.java:77) ~[?:?]
at com.sk89q.worldedit.function.RegionMaskingFilter.apply(RegionMaskingFilter.java:53) ~[?:?]
at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:60) ~[?:?]
at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:91) ~[?:?]
at com.sk89q.worldedit.function.operation.DelegateOperation.resume(DelegateOperation.java:52) ~[?:?]
at com.sk89q.worldedit.function.operation.Operations.complete(Operations.java:41) ~[?:?]
at com.ryandw11.structure.schematic.SchematicHandler.createSchematic(SchematicHandler.java:272) ~[?:?]
at com.ryandw11.structure.commands.cstruct.CreateSchematicCommand.subCommand(CreateSchematicCommand.java:44) ~[?:?]
at com.ryandw11.structure.commands.CommandHandler.handleCommand(CommandHandler.java:69) ~[?:?]
at com.ryandw11.structure.commands.SCommand.onCommand(SCommand.java:46) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
... 23 more

**Comment by ryandw11** [comment]
```
Caused by: java.lang.IllegalAccessError: class com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R1.PaperweightAdapter tried to access private field net.minecraft.nbt.NBTTagCompound.x 
(com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R1.PaperweightAdapter is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @f7915a7; 
net.minecraft.nbt.NBTTagCompound is in unnamed module of loader java.net.URLClassLoader @6a4f1a55)
```

This appears to be world edit bug. Try updating to World Edit version 7.3.1.

**Comment by Yesu321** [comment]
> ```
> Caused by: java.lang.IllegalAccessError: class com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R1.PaperweightAdapter tried to access private field net.minecraft.nbt.NBTTagCompound.x 
> (com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R1.PaperweightAdapter is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @f7915a7; 
> net.minecraft.nbt.NBTTagCompound is in unnamed module of loader java.net.URLClassLoader @6a4f1a55)
> ```
> 
> This appears to be world edit bug. Try updating to World Edit version 7.3.1.

Thank you very much, now it works for me :D
