### ISSUE TITLE
task #32 for customstructure v1.3.3 generated an exception

### ISSUE THREAD

**Issue by Imziqi** [ryandw11/CustomStructures#28]
this is spaming my console:
task #32 for customstructure v1.3.3 generated an exception
i dont know why
the schems works and plugin is not red in /pl

**Comment by Imziqi** [comment]
[Server thread/WARN]: [CustomStructures] Task #32 for CustomStructures v1.3.3 generated an exception
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.ryandw11.structure.utils.CheckSchematics.run(CheckSchematics.java:29) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[spigot.jar:git-Paper-1610]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[spigot.jar:git-Paper-1610]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
[16:10:28] [Server thread/WARN]: [CustomStructures] Task #32 for CustomStructures v1.3.3 generated an exception
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.ryandw11.structure.utils.CheckSchematics.run(CheckSchematics.java:29) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[spigot.jar:git-Paper-1610]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[spigot.jar:git-Paper-1610]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
[16:10:28] [Server thread/WARN]: [CustomStructures] Task #32 for CustomStructures v1.3.3 generated an exception
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.ryandw11.structure.utils.CheckSchematics.run(CheckSchematics.java:29) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[spigot.jar:git-Paper-1610]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[spigot.jar:git-Paper-1610]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
[16:10:28] [Server thread/WARN]: [CustomStructures] Task #32 for CustomStructures v1.3.3 generated an exception
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.ryandw11.structure.utils.CheckSchematics.run(CheckSchematics.java:29) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[spigot.jar:git-Paper-1610]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[spigot.jar:git-Paper-1610]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
[16:10:28] [Server thread/WARN]: [CustomStructures] Task #32 for CustomStructures v1.3.3 generated an exception
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.ryandw11.structure.utils.CheckSchematics.run(CheckSchematics.java:29) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[spigot.jar:git-Paper-1610]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[spigot.jar:git-Paper-1610]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[spigot.jar:git-Paper-1610]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]

**Comment by Imziqi** [comment]
its spaming this on my console

**Comment by Imziqi** [comment]
if it can be fixed i'll be really glad : )

**Comment by ryandw11** [comment]
Can I see your config file?

**Comment by Imziqi** [comment]
ok

**Comment by Imziqi** [comment]
> Can I see your config file?

do i send the file or the text?

**Comment by Imziqi** [comment]
im running on papserspigot 1.12.2 core
and plugin is 1.3.3

**Comment by Imziqi** [comment]
heres the config file:

configversion: 3
#========================================
#             Custom Structures    
#========================================
#Wiki: https://github.com/ryandw11/CustomStructures/wiki
Schematics:

#A list containing all of the schematics.
#When you add a new schematic add it to this list.
    List:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - Jungle
        - Temple
    1:
        Schematic: '1.schematic'
        Biome: 'all'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: -1
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Grass_block
            - Dirt
            - Stone
    2:
        Schematic: '2.schematic'
        Biome: 'all'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: -1
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Grass_block
            - Dirt
            - Stone
    3:
        Schematic: '3.schematic'
        Biome: 'all'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: -1
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Grass_block
            - Dirt
            - Stone
    Jungle:
        Schematic: 'Jungle.schematic'
        Biome: 'JUNGLE'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: 0
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Grass_block
            - Dirt
    Temple:
        Schematic: 'Temple.schematic'
        Biome: 'all'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: 0
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Stone
            - Water
            - Grass_block
    4:
        Schematic: '4.schematic'
        Biome: 'PLAINS'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: 0
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Grass_block
    5:
        Schematic: '5.schematic'
        Biome: 'DESERT'
        Chance:
            Number: 1
            OutOf: 2000
        AllWorlds: false
        SpawnY: -2
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Sand
    6:
        Schematic: '6.schematic'
        Biome: 'DESERT'
        Chance:
            Number: 1
            OutOf: 2000
        AllWorlds: false
        SpawnY: -2
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Sand
    7:
        Schematic: '7.schematic'
        Biome: 'STONE_SHORE'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: 0
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Stone
    8:
        Schematic: '8.schematic'
        Biome: 'JUNGLE'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: -1
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Grass_block
    9:
        Schematic: '9.schematic'
        Biome: 'JUNGLE'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: 0
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Grass_block
    10:
        Schematic: '10.schematic'
        Biome: 'all'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: 0
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Grass_block
    11:
        Schematic: '11.schematic'
        Biome: 'all'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: 0
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Grass_block
    12:
        Schematic: '12.schematic'
        Biome: 'all'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: 0
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Grass_block
    13:
        Schematic: '13.schematic'
        Biome: 'all'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: 0
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Grass_block
    14:
        Schematic: '14.schematic'
        Biome: 'all'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: 0
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Grass_block  
    15:
        Schematic: '15.schematic'
        Biome: 'all'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: 0
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Grass_block
    16:
        Schematic: '16.schematic'
        Biome: 'all'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: 0
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Grass_block
    17:
        Schematic: '17.schematic'
        Biome: 'all'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: 0
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Grass_block
    18:
        Schematic: '18.schematic'
        Biome: 'all'
        Chance:
            Number: 1
            OutOf: 3000
        AllWorlds: false
        SpawnY: 0
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Grass_block
    19:
        Schematic: '19.schematic'
        Biome: 'all'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: false
        SpawnY: 0
        PlaceAir: true
        AllowedWorlds:
            - world2
        randomRotation: true
        whitelistSpawnBlocks:
            - Grass_block

**Comment by Imziqi** [comment]
it didn't get the tab and space done

**Comment by Imziqi** [comment]
it is good if u can write the version where the config is added in the instructions

**Comment by ryandw11** [comment]
Can you surround it with three backquotes ` ``` `
or paste it here: https://pastebin.com/

**Comment by Imziqi** [comment]
https://pastebin.com/u4GQ16ai
the code is here 
if u can help me fix the problem i'll be really glad

**Comment by ryandw11** [comment]
Out of date version. If the issue persists on 1.4.3 then please make another bug report.
