### ISSUE TITLE
Issue with generation

### ISSUE THREAD

**Issue by LucianDevran** [ryandw11/CustomStructures#4]
I have an Issue:
Only the Demo schematic spawns...

My config: https://pastebin.com/wSZM4TDv

There are no Errors.

I use FAWE and other plugins but i don´t think they affect Custom Structures since they dont affect Worldedit

Edit:
When using /cs test Tower
I get this error

`[code][21:26:23] [Server thread/WARN]: [CustomStructures] Error: The schematic null does not exist!
[21:26:23] [Server thread/WARN]: [CustomStructures] If this is your first time using this plugin you need to put a schematic in the schematic folder.
[21:26:23] [Server thread/WARN]: [CustomStructures] Then add it into the config.
[21:26:23] [Server thread/WARN]: [CustomStructures] If you need help look at the wiki: https://github.com/ryandw11/CustomStructures/wiki or contact Ryandw11 on spigot!
[21:26:23] [Server thread/WARN]: [CustomStructures] The plugin will now disable to prevent damage to the server.
[21:26:23] [Server thread/INFO]: [CustomStructures] Disabling CustomStructures v1.3.3[/code]`

Edit 2:

So the schematics themselves are fine... If I rename a schematic to demo it will work with this schematic. Although the same schematic wont work with another name

Edit 3:
Demo also doesnt place air but I set it to true

**Comment by ryandw11** [comment]
Ok. I will look into this. I will also look into the air setting.

**Comment by ryandw11** [comment]
I'm having trouble replicating the bug. The error says the schematics doesn't exist. Do the schematic files in the schematic folder have the same names as they do in the config file?

**Comment by LucianDevran** [comment]
Alright i can provide you with some more information i gathered. 

I found the demo structure spawning in the Nether and clearing all its surrounding. (so it did spawn with air)
Although when I spawn it in my other world it wont clear land.
This let me to the conclusion this might be an bug with Multiverse since the world im trying to use it with is a Multiverse world.
But in the Normal world also doesn´t spawns with air.


But now to your request. 
https://www.mediafire.com/#3a40jv4zbhcaq
This are the schematic files i use. 

Also here is a list of my plugins:

armorstandeditor
Builders-Wand
ChestCleaner
ChopTree4
CrazyEnchantment
CrazyCrates
Cs-CoreLib
CustomStructures
DeathChest
EssentialsX(2.0.1)
EssentialsXChat
FAWE
Healthbar (which i dont use currently)
Hologramms
InfernalMobs
KillerMoney
Minepacks
MultipleResources
Muliverse-Core
Multiverse-Portals
MusiCraft
PermissionsEX
Shopkeeper(also not in use)
Silkspawners
SlimeFun
Sudo
Vault
WorldBorder
WorldEdit
XPBoost


I hope this helps you

**Comment by LucianDevran** [comment]
I found an Error paste in my latest log....
`[13:00:44] [Server thread/ERROR]: Cannot load plugins/CustomStructures/config.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 11, column 5:
        List:
        ^
expected <block end>, but found BlockMappingStart
 in 'string', line 71, column 6:
         desert-dungeon:
         ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) [craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:160) [craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:135) [craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at com.ryandw11.structure.CustomStructures.onEnable(CustomStructures.java:42) [CustomStructures.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 11, column 5:
        List:
        ^
expected <block end>, but found BlockMappingStart
 in 'string', line 71, column 6:
         desert-dungeon:
         ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:569) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:122) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:424) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[craftbukkit.jar:git-Spigot-7754231-9a1f5ee]
	... 17 more`

**Comment by LucianDevran** [comment]
https://pastebin.com/ZmC1ib21
I found this Error in my latest server log

**Comment by ryandw11** [comment]
Try this config.
https://pastebin.com/HGaNSnuj

**Comment by LucianDevran** [comment]
Yeah this works!

Thank you very much ^^

What was Error?

**Comment by ryandw11** [comment]
There was an extra space in front of desert-dungeon. Yaml requires the exact amount of space. I should of checked to see if the config was valid first. It would have saved a lot of time.
