### ISSUE TITLE
Loot in chests

### ISSUE THREAD

**Issue by Bambicek** [ryandw11/CustomStructures#53]
**Console error:**
[09:34:09 WARN]: [CustomStructures] Task #47724 for CustomStructures vSpecial 1.12.2 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/block/Container
        at com.ryandw11.structure.SchematicHandeler.getContainersAndSignsLocations(SchematicHandeler.java:156) ~[?:?]
        at com.ryandw11.structure.SchematicHandeler.lambda$0(SchematicHandeler.java:113) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by ryandw11** [comment]
Likely fixed in 1.5
