### ISSUE TITLE
Problems on 1.13

### ISSUE THREAD

**Issue by Xuwznln** [ryandw11/CustomStructures#7]
I got this error. I am using the latest build of fawe and customstructures.
[19:59:53] [Server thread/ERROR]: Could not pass event ChunkLoadEvent to CustomStructures v1.3.4-Pre2
java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat, but interface was expected
	at com.ryandw11.structure.SchematicHandeler.schemHandle(SchematicHandeler.java:55) ~[?:?]
	at com.ryandw11.structure.utils.Structures.chooseBestStructure(Structures.java:60) ~[?:?]
	at com.ryandw11.structure.listener.ChunkLoad.loadevent(ChunkLoad.java:52) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor197.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[spigot.jar:git-Paper-294]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-Paper-294]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Paper-294]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[spigot.jar:git-Paper-294]
	at net.minecraft.server.v1_13_R2.Chunk.addEntities(Chunk.java:986) ~[spigot.jar:git-Paper-294]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:1682) ~[spigot.jar:git-Paper-294]
	at net.minecraft.server.v1_13_R2.MinecraftServer.postToMainThread(MinecraftServer.java:1691) ~[spigot.jar:git-Paper-294]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.a(ChunkProviderServer.java:213) ~[spigot.jar:git-Paper-294]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983) ~[?:1.8.0_161]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:124) ~[spigot.jar:git-Paper-294]
	at net.minecraft.server.v1_13_R2.PlayerChunk.a(PlayerChunk.java:98) ~[spigot.jar:git-Paper-294]
	at net.minecraft.server.v1_13_R2.PlayerChunkMap.flush(PlayerChunkMap.java:159) ~[spigot.jar:git-Paper-294]
	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:322) ~[spigot.jar:git-Paper-294]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1076) ~[spigot.jar:git-Paper-294]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[spigot.jar:git-Paper-294]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:945) ~[spigot.jar:git-Paper-294]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:843) ~[spigot.jar:git-Paper-294]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

Please fix that! Thanks!

**Comment by ryandw11** [comment]
when you do /ver customstructures what does it print out?

**Comment by Xuwznln** [comment]
It is 1.3.4-pre2
I tested with worldedit 7.0 snapshot. It works. But these scheme seems not working correctly with its probability.

**Comment by Xuwznln** [comment]
Schematics:

#A list containing all of the schematics.
#When you add a zd schematic add it to this list.
    List:
        - jiyan1
        - jiyan2
        - jiyan3
        - jiyan4
        - jiyan5
        - jiyan6
        - jiyan7
        - tie4
        - tie3
        - tie2
        - tie1
        - shiying7
        - shiying6
        - shiying5
        - shiying4
        - shiying3
        - shiying2
        - shiying1
        - qingjinshi5
        - qingjinshi4
        - qingjinshi3
        - qingjinshi2
        - qingjinshi1
        - mei5
        - mei4
        - mei3
        - mei2
        - mei1
        - lvbaoshi1
        - lvbaoshi2
        - lvbaoshi3
        - lvbaoshi4
        - lvbaoshi5
        - jin4
        - jin3
        - jin2
        - jin1
        - hongs6
        - hongs5
        - hongs4
        - hongs3
        - hongs2
        - hongs1

Each one set like this.
    qingjinshi5:
        Schematic: 'qingjinshi5.schem'
        Biome: 'all'
        Chance:
            Number: 1
            OutOf: 5
        AllWorlds: false
        SpawnY: 33
        OffSet: 3
        PlaceAir: true
        AllowedWorlds:
            - zd
            - new

But I actually get this world (I use an empty to see the generate results.)
http://i1.bvimg.com/505666/a86b36690b0dbfca.png

**Comment by ryandw11** [comment]
I should be as when it picks 1-5 and compares it to the number. So the chance should be 1/5

**Comment by Xuwznln** [comment]
ok, And can you make it support fawe？

**Comment by ryandw11** [comment]
For some reason I think the fawe api and the worldedit api are different in 1.13. I will try to add fawe support into the plugin.
